# Generated by Django 5.0.7 on 2025-09-20 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Phòng ban', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Quản lý'), ('hcns', 'Hành chính nhân sự'), ('employee', 'Nhân viên')], default='employee', help_text='Vai trò của người dùng trong hệ thống', max_length=20),
        ),
    ]
