# Generated by Django 5.0.7 on 2025-09-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_department_deputy_manager_department_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên loại vắng mặt', max_length=100)),
                ('code', models.CharField(help_text='Mã loại vắng mặt', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả')),
                ('requires_approval', models.BooleanField(default=True, help_text='Cần phê duyệt')),
                ('max_days_per_year', models.IntegerField(blank=True, help_text='Số ngày tối đa/năm', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Đang hoạt động')),
                ('color', models.CharField(default='#3B82F6', help_text='Màu hiển thị', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loại vắng mặt',
                'verbose_name_plural': 'Loại vắng mặt',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Ngày bắt đầu')),
                ('end_date', models.DateField(help_text='Ngày kết thúc')),
                ('start_time', models.TimeField(blank=True, help_text='Giờ bắt đầu', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Giờ kết thúc', null=True)),
                ('total_days', models.DecimalField(decimal_places=1, help_text='Tổng số ngày', max_digits=4)),
                ('reason', models.TextField(help_text='Lý do')),
                ('attachment', models.FileField(blank=True, help_text='File đính kèm', null=True, upload_to='absence_attachments/')),
                ('approval_level', models.CharField(default='department_manager', help_text='Cấp phê duyệt hiện tại', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], default='pending', help_text='Trạng thái', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Thời gian phê duyệt', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Lý do từ chối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Người phê duyệt cuối cùng', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_absences', to=settings.AUTH_USER_MODEL)),
                ('current_approver', models.ForeignKey(blank=True, help_text='Người phê duyệt hiện tại', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Người tạo đơn', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('absence_type', models.ForeignKey(help_text='Loại vắng mặt', on_delete=django.db.models.deletion.CASCADE, to='absence.absencetype')),
            ],
            options={
                'verbose_name': 'Đơn vắng mặt',
                'verbose_name_plural': 'Đơn vắng mặt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('forwarded', 'Chuyển tiếp')], help_text='Hành động', max_length=20)),
                ('level', models.CharField(help_text='Cấp phê duyệt', max_length=50)),
                ('comment', models.TextField(blank=True, help_text='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absence_request', models.ForeignKey(help_text='Đơn vắng mặt', on_delete=django.db.models.deletion.CASCADE, to='absence.absencerequest')),
                ('approver', models.ForeignKey(help_text='Người phê duyệt', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử phê duyệt',
                'verbose_name_plural': 'Lịch sử phê duyệt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_department_manager', models.BooleanField(default=True, help_text='Cần Trưởng phòng')),
                ('requires_department_deputy', models.BooleanField(default=False, help_text='Cần Phó phòng')),
                ('requires_office_director', models.BooleanField(default=False, help_text='Cần Giám đốc VP')),
                ('requires_office_deputy', models.BooleanField(default=False, help_text='Cần Phó GĐ VP')),
                ('requires_hr_approval', models.BooleanField(default=True, help_text='Cần HR')),
                ('department_manager_priority', models.IntegerField(default=1, help_text='Ưu tiên Trưởng phòng')),
                ('department_deputy_priority', models.IntegerField(default=2, help_text='Ưu tiên Phó phòng')),
                ('office_director_priority', models.IntegerField(default=3, help_text='Ưu tiên Giám đốc VP')),
                ('office_deputy_priority', models.IntegerField(default=4, help_text='Ưu tiên Phó GĐ VP')),
                ('department_manager_timeout_hours', models.IntegerField(default=24, help_text='Timeout Trưởng phòng (giờ)')),
                ('department_deputy_timeout_hours', models.IntegerField(default=24, help_text='Timeout Phó phòng (giờ)')),
                ('office_director_timeout_hours', models.IntegerField(default=48, help_text='Timeout Giám đốc VP (giờ)')),
                ('office_deputy_timeout_hours', models.IntegerField(default=48, help_text='Timeout Phó GĐ VP (giờ)')),
                ('hr_timeout_hours', models.IntegerField(default=24, help_text='Timeout HR (giờ)')),
                ('send_reminder_before_hours', models.IntegerField(default=2, help_text='Gửi nhắc nhở trước (giờ)')),
                ('max_reminders', models.IntegerField(default=3, help_text='Số lần nhắc nhở tối đa')),
                ('is_active', models.BooleanField(default=True, help_text='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence_type', models.ForeignKey(help_text='Loại vắng mặt', on_delete=django.db.models.deletion.CASCADE, to='absence.absencetype')),
                ('department', models.ForeignKey(help_text='Phòng ban', on_delete=django.db.models.deletion.CASCADE, to='users.department')),
            ],
            options={
                'verbose_name': 'Workflow phê duyệt',
                'verbose_name_plural': 'Workflow phê duyệt',
                'unique_together': {('department', 'absence_type')},
            },
        ),
        migrations.AddField(
            model_name='absencerequest',
            name='workflow',
            field=models.ForeignKey(help_text='Workflow', on_delete=django.db.models.deletion.CASCADE, to='absence.approvalworkflow'),
        ),
    ]
