# Generated by Django 5.0.7 on 2025-09-26 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.TextField(blank=True, help_text='Địa chỉ được lấy từ reverse geocoding')),
                ('photo', models.ImageField(upload_to='checkins/%Y/%m/%d/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('checkin_type', models.CharField(choices=[('1', 'Chấm công'), ('2', 'Tiếp khách')], default='1', help_text='Loại check-in', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_checkins', 'Can manage checkins'), ('can_view_checkins', 'Can view checkins'), ('can_create_checkins', 'Can create checkins'), ('can_edit_checkins', 'Can edit checkins'), ('can_delete_checkins', 'Can delete checkins'), ('can_view_all_checkins', 'Can view all checkins'), ('can_view_own_checkins', 'Can view own checkins'), ('can_view_checkin_reports', 'Can view checkin reports'), ('can_export_checkin_data', 'Can export checkin data')],
            },
        ),
    ]
