# Generated by Django 5.0.7 on 2025-09-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_checkins', 'Can manage checkins'), ('can_view_checkins', 'Can view checkins'), ('can_create_checkins', 'Can create checkins'), ('can_edit_checkins', 'Can edit checkins'), ('can_delete_checkins', 'Can delete checkins'), ('can_view_all_checkins', 'Can view all checkins'), ('can_view_own_checkins', 'Can view own checkins'), ('can_view_checkin_reports', 'Can view checkin reports'), ('can_export_checkin_data', 'Can export checkin data')], 'verbose_name': 'Check-in', 'verbose_name_plural': 'Check-ins'},
        ),
    ]
