# Generated by Django 5.0.7 on 2025-09-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_alter_checkin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='checkin_type',
            field=models.CharField(choices=[('1', 'Chấm công'), ('2', 'Tiếp khách')], default='1', help_text='Loại check-in', max_length=1),
        ),
    ]
