# Generated by Django 5.0.7 on 2025-09-26 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_remove_area_references'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.TextField(blank=True, help_text='Địa chỉ được lấy từ reverse geocoding')),
                ('photo', models.ImageField(upload_to='checkouts/%Y/%m/%d/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('checkin', models.ForeignKey(help_text='Checkin tương ứng với checkout này', on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='checkin.checkin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check-out',
                'verbose_name_plural': 'Check-outs',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_checkouts', 'Can manage checkouts'), ('can_view_checkouts', 'Can view checkouts'), ('can_create_checkouts', 'Can create checkouts'), ('can_edit_checkouts', 'Can edit checkouts'), ('can_delete_checkouts', 'Can delete checkouts'), ('can_view_all_checkouts', 'Can view all checkouts'), ('can_view_own_checkouts', 'Can view own checkouts'), ('can_view_checkout_reports', 'Can view checkout reports'), ('can_export_checkout_data', 'Can export checkout data')],
            },
        ),
    ]
