# Generated by Django 5.0.7 on 2025-09-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_checkin_checkin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='address',
            field=models.TextField(blank=True, help_text='Địa chỉ được lấy từ reverse geocoding'),
        ),
    ]
