# Generated by Django 5.0.7 on 2025-09-23 01:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên phòng ban', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả phòng ban')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': 'Phòng ban',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Quản trị viên'), ('manager', 'Quản lý'), ('hcns', 'Nhân sự'), ('employee', 'Nhân viên')], default='employee', help_text='Vai trò người dùng', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Số điện thoại', max_length=20)),
                ('avatar', models.ImageField(blank=True, help_text='Ảnh đại diện', null=True, upload_to='avatars/')),
                ('date_of_birth', models.DateField(blank=True, help_text='Ngày sinh', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], help_text='Giới tính', max_length=10)),
                ('address', models.TextField(blank=True, help_text='Địa chỉ')),
                ('emergency_contact', models.CharField(blank=True, help_text='Người liên hệ khẩn cấp', max_length=100)),
                ('emergency_phone', models.CharField(blank=True, help_text='Số điện thoại liên hệ khẩn cấp', max_length=20)),
                ('position', models.CharField(blank=True, help_text='Chức vụ', max_length=100)),
                ('hire_date', models.DateField(blank=True, help_text='Ngày vào làm', null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Lương', max_digits=12, null=True)),
                ('work_schedule', models.CharField(blank=True, help_text='Lịch làm việc', max_length=100)),
                ('skills', models.TextField(blank=True, help_text='Kỹ năng')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú')),
                ('is_active_employee', models.BooleanField(default=True, help_text='Nhân viên đang hoạt động')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, help_text='Phòng ban', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
