# Generated by Django 5.0.7 on 2025-09-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('can_manage_users', 'Can manage users'), ('can_view_users', 'Can view users'), ('can_create_users', 'Can create users'), ('can_edit_users', 'Can edit users'), ('can_delete_users', 'Can delete users'), ('can_manage_departments', 'Can manage departments'), ('can_view_departments', 'Can view departments'), ('can_create_departments', 'Can create departments'), ('can_edit_departments', 'Can edit departments'), ('can_delete_departments', 'Can delete departments'), ('can_manage_roles', 'Can manage user roles'), ('can_assign_roles', 'Can assign roles to users'), ('can_access_admin', 'Can access admin panel'), ('can_manage_system', 'Can manage system settings')], 'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
    ]
