# Generated by Django 5.0.7 on 2025-09-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Mã nhân viên', max_length=20, null=True, unique=True),
        ),
    ]
