# Generated by Django 5.0.7 on 2025-09-24 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên văn phòng', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả văn phòng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Văn phòng',
                'verbose_name_plural': 'Văn phòng',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['office__name', 'name'], 'verbose_name': 'Phòng ban', 'verbose_name_plural': 'Phòng ban'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Tên phòng ban', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='office',
            field=models.ForeignKey(help_text='Văn phòng', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.office'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'office')},
        ),
    ]
