# Generated by Django 5.0.7 on 2025-09-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_office_to_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='deputy_manager',
            field=models.ForeignKey(blank=True, help_text='Phó phòng', limit_choices_to={'role__in': ['admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Trưởng phòng', limit_choices_to={'role__in': ['admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='office',
            name='deputy_director',
            field=models.ForeignKey(blank=True, help_text='Phó Giám đốc Văn phòng', limit_choices_to={'role__in': ['admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_directed_offices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='office',
            name='director',
            field=models.ForeignKey(blank=True, help_text='Giám đốc Văn phòng', limit_choices_to={'role__in': ['admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_offices', to=settings.AUTH_USER_MODEL),
        ),
    ]
