# Generated by Django 5.0.7 on 2025-09-26 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('users', '0005_department_deputy_manager_department_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Địa điểm của văn phòng', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
    ]
