# Generated by Django 5.0.7 on 2025-09-26 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('checkin', 'Check-in System'), ('location', 'Location Management'), ('users', 'User Management'), ('dashboard', 'Dashboard'), ('notifications', 'Notifications'), ('absence', 'Absence Management'), ('reports', 'Reports'), ('analytics', 'Analytics'), ('automation_test', 'Automation Testing')], help_text='Tên module', max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Module có được bật hay không')),
                ('display_name', models.CharField(help_text='Tên hiển thị của module', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Mô tả chức năng của module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo setting', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module Setting',
                'verbose_name_plural': 'Module Settings',
                'ordering': ['module_name'],
            },
        ),
    ]
