# Generated by Django 5.0.7 on 2025-09-26 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên địa điểm', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Mô tả địa điểm')),
                ('address', models.TextField(blank=True, help_text='Địa chỉ chi tiết')),
                ('lat', models.FloatField(help_text='Vĩ độ trung tâm')),
                ('lng', models.FloatField(help_text='Kinh độ trung tâm')),
                ('radius_m', models.PositiveIntegerField(default=100, help_text='Bán kính (mét)')),
                ('is_active', models.BooleanField(default=True, help_text='Địa điểm có hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo địa điểm', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Địa điểm',
                'verbose_name_plural': 'Địa điểm',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_locations', 'Can manage locations'), ('can_view_locations', 'Can view locations'), ('can_create_locations', 'Can create locations'), ('can_edit_locations', 'Can edit locations'), ('can_delete_locations', 'Can delete locations'), ('can_activate_locations', 'Can activate/deactivate locations')],
            },
        ),
    ]
