# Generated by Django 5.0.7 on 2025-09-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên khu vực', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Mô tả khu vực')),
                ('lat', models.FloatField(help_text='Vĩ độ trung tâm')),
                ('lng', models.FloatField(help_text='Kinh độ trung tâm')),
                ('radius_m', models.PositiveIntegerField(default=100, help_text='Bán kính (mét)')),
                ('is_active', models.BooleanField(default=True, help_text='Khu vực có hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khu vực',
                'verbose_name_plural': 'Khu vực',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('photo', models.ImageField(upload_to='checkins/%Y/%m/%d/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('radius_m', models.PositiveIntegerField(default=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
