# Generated by Django 5.0.7 on 2025-09-16 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkin.location'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên khu vực', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Mô tả khu vực')),
                ('lat', models.FloatField(help_text='Vĩ độ trung tâm')),
                ('lng', models.FloatField(help_text='Kinh độ trung tâm')),
                ('radius_m', models.PositiveIntegerField(default=100, help_text='Bán kính (mét)')),
                ('is_active', models.BooleanField(default=True, help_text='Khu vực có hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Người tạo khu vực', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Khu vực',
                'verbose_name_plural': 'Khu vực',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='checkin',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkin.area'),
        ),
    ]
