# Generated by Django 5.0.7 on 2025-09-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_area_created_by_checkin_area_checkin_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
