# Generated by Django 5.0.7 on 2025-09-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_areas', 'Can manage areas'), ('can_view_areas', 'Can view areas'), ('can_create_areas', 'Can create areas'), ('can_edit_areas', 'Can edit areas'), ('can_delete_areas', 'Can delete areas'), ('can_activate_areas', 'Can activate/deactivate areas')], 'verbose_name': 'Khu vực', 'verbose_name_plural': 'Khu vực'},
        ),
    ]
