# Generated by Django 5.0.7 on 2025-09-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề', max_length=200)),
                ('message', models.TextField(help_text='Nội dung')),
                ('type', models.CharField(choices=[('approval_required', 'Cần phê duyệt'), ('approval_completed', 'Đã phê duyệt'), ('approval_rejected', 'Bị từ chối'), ('reminder', 'Nhắc nhở'), ('system', 'Hệ thống'), ('checkin', 'Chấm công'), ('absence', 'Vắng mặt')], help_text='Loại thông báo', max_length=50)),
                ('is_read', models.BooleanField(default=False, help_text='Đã đọc')),
                ('is_important', models.BooleanField(default=False, help_text='Quan trọng')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Dữ liệu bổ sung')),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID đối tượng liên quan', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Loại đối tượng liên quan', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Thời gian đọc', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Thời gian hết hạn', null=True)),
                ('user', models.ForeignKey(help_text='Người nhận', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'type'], name='notificatio_user_id_827754_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
